//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solidsoft.Reply.Parsers.HighCapacityAidc.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Solidsoft.Reply.Parsers.HighCapacityAidc.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szöveg.
        /// </summary>
        internal static string Barcodes_001 {
            get {
                return ResourceManager.GetString("Barcodes_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szabad formátumú szöveg..
        /// </summary>
        internal static string Barcodes_002 {
            get {
                return ResourceManager.GetString("Barcodes_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDI.
        /// </summary>
        internal static string Barcodes_003 {
            get {
                return ResourceManager.GetString("Barcodes_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teljes EDI üzenet/tranzakció..
        /// </summary>
        internal static string Barcodes_004 {
            get {
                return ResourceManager.GetString("Barcodes_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strukturált adatok.
        /// </summary>
        internal static string Barcodes_005 {
            get {
                return ResourceManager.GetString("Barcodes_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szövegelem azonosító szabályai szerinti strukturált adatok..
        /// </summary>
        internal static string Barcodes_006 {
            get {
                return ResourceManager.GetString("Barcodes_006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASC X12.
        /// </summary>
        internal static string Barcodes_007 {
            get {
                return ResourceManager.GetString("Barcodes_007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ANSI ASC X12 szegmensekkel rendelkező strukturált adatok..
        /// </summary>
        internal static string Barcodes_008 {
            get {
                return ResourceManager.GetString("Barcodes_008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UN EDIFACT.
        /// </summary>
        internal static string Barcodes_009 {
            get {
                return ResourceManager.GetString("Barcodes_009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UN/EDIFACT szegmensekkel rendelkező strukturált adatok..
        /// </summary>
        internal static string Barcodes_010 {
            get {
                return ResourceManager.GetString("Barcodes_010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CII [{0}{1}{2}].
        /// </summary>
        internal static string Barcodes_011 {
            get {
                return ResourceManager.GetString("Barcodes_011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CII szintaktikai szabályokkal rendelkező strukturált adatok..
        /// </summary>
        internal static string Barcodes_012 {
            get {
                return ResourceManager.GetString("Barcodes_012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bináris adatok [{0}; {1}; {2} bájt].
        /// </summary>
        internal static string Barcodes_013 {
            get {
                return ResourceManager.GetString("Barcodes_013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bináris adatok (fájltípus) (tömörítési technika) (bájtok száma)..
        /// </summary>
        internal static string Barcodes_014 {
            get {
                return ResourceManager.GetString("Barcodes_014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nincsenek vonalkód adatok..
        /// </summary>
        internal static string Barcodes_Error_001 {
            get {
                return ResourceManager.GetString("Barcodes_Error_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A vonalkód adatok előfeldolgozása sikertelen..
        /// </summary>
        internal static string Barcodes_Error_002 {
            get {
                return ResourceManager.GetString("Barcodes_Error_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A vonalkód kódolása nem támogatott..
        /// </summary>
        internal static string Barcodes_Error_003 {
            get {
                return ResourceManager.GetString("Barcodes_Error_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A vonalkód érvénytelen vagy fel nem ismert adatokat tartalmaz..
        /// </summary>
        internal static string Barcodes_Error_004 {
            get {
                return ResourceManager.GetString("Barcodes_Error_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A vonalkód érvénytelen adatbejegyzést tartalmaz..
        /// </summary>
        internal static string Barcodes_Error_005 {
            get {
                return ResourceManager.GetString("Barcodes_Error_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Az elemző nem támogatja a {0} bejegyzés szintaktikáját és szemantikáját..
        /// </summary>
        internal static string Barcodes_Error_006 {
            get {
                return ResourceManager.GetString("Barcodes_Error_006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A vonalkódban lévő adatbejegyzés formátuma fel nem ismert..
        /// </summary>
        internal static string Barcodes_Error_007 {
            get {
                return ResourceManager.GetString("Barcodes_Error_007", resourceCulture);
            }
        }
    }
}
